export const GAMEWIDTH = 176;
export const GAMEHEIGHT = 168;
export const BORDERTHICKLEFT = 24;
export const BORDERTHICKRIGHT = 24;
export const BORDERTHICKTOP = 20;
export const BORDERTHICKBOTTOM = 20;
export const RIGHT = "right";
export const LEFT = "left";
export const CENTER = "center";
export const CLICKRIGHT = "right";
export const CLICKLEFT = "left";
export const DEV = localStorage.getItem("is_dev") == "true";
