export const bookPages: string[] = [
  `  Reach the lowest level you can!\n\n  Levels are made of grids of blocks, to start the first level click on any block.\n\n  Clicking on a block will break it and reveal adjacent blocks. Once a level starts you can only break blocks that have been revealed.\n  Blocks may or may not contain a worm $wrm inside them, if you break a block with a worm you'll have to fight it!\n\n  A broken block will show a number if there are any worms in blocks surrounding it, the ammount of worms corresponding to the number.`,

  `  A broken block with no number has no worms surrounding it, so it's safe to break around it.\n  You can Right Click any block you suspect may contain a worm to mark it. Marked blocks cannot be broken.\n\n  Each mark will reduce the $wrm worm counter. Breaking a block that doesn't have a worm will reduce the $blk blocks counter. Reducing both counters to 0 is clearing a room, which will reward you with 5 $gld gold!\n\n  $gld Gold can also be obtained by breaking any block with gold ores in them, they're worth 1 gold.\n  You can use your gold to buy useful items at a shop.`,

  `  Inside every level you can find doors. Green doors will take you to the $dor next level and give you 60 $tim seconds while brown doors take you to a shop where you can buy and sell items.\n\n  When fighting a worm, you'll use your gear to attack and defend against it. Hover your mouse over items in your inventory to see their stats and descriptions.\n\n  Left Clicking will use your weapon and Right Clicking will use your shield.\n\n  Weapons and shields both have a timer for $spd cooldown, once you use them in battle you have to wait to make another action.`,

  `  Attacking will reduce the enemy's health by your weapon's $dmg damage value, and using your shield will grant you $dfs defense points for its defense value.\n\n  Enemy $dmg damage is reduced by your $dfs defense. Defense goes down per $dmg damage taken.\n\n  Armor can give you $pro protection, which works the same as defense but does not get reduced by enemy attacks.\n\n  It can also give you initial $dfs defense, as well as making your cooldown time $spd shorter or $slw longer.`,

  `  Enemies also have their own $spd timers for attacking, so get ready to get enough $dfs defense before they do!\n\n  $ref Reflection also counts as defense. Each point of reflection reduced by enemy $dmg damage will deal one point of damage back to the enemy.\n\n  $spk Spikes are damage dealt against attacker, when an enemy attacks you, all your spike points are turned into damage back at them.\n\n  All attribute rules  apply both for enemies and for you.\n\n  If an enemy runs out of $hrt health and die, the $wrm worm counter goes down`,

  `  If you run out of $hrt health you $skl lose.\n\n  $tim Time moves anywhere outside of a shop. If you ever run out of time, you $skl lose.\n\n  Enemies get stronger and faster the deeper you are in the game. $dor Makrs the current level you're on.\n\n  So get ready to mine, battle and to sweep some worms!`,
];
