import Position from "../gameElements/position.js";
import { Item } from "./item.js";
const passivesDict = {
    gold_bug: new Item({
        spriteSheetPos: new Position(0, 4),
        name: "gold_bug",
        shopName: "Gold Bug",
        cost: 20,
        descriptionText: "More gold during caves and when clearing levels. More worms. The bug's curse is ever lasting.",
    }),
    feather: new Item({
        spriteSheetPos: new Position(2, 4),
        name: "feather",
        shopName: "Feather",
        cost: 21,
        descriptionText: "Reduces weapon $spdcooldown by 0.3 Seconds.",
    }),
    dark_crystal: new Item({
        spriteSheetPos: new Position(4, 4),
        name: "dark_crystal",
        shopName: "Dark Crystal",
        cost: 15,
        descriptionText: "Allows you to break blocks you can't see.",
    }),
    detonator: new Item({
        spriteSheetPos: new Position(6, 4),
        name: "detonator",
        shopName: "Detonator",
        cost: 20,
        descriptionText: "Use this to break all unmarked blocks around a block instantly.",
    }),
    drill: new Item({
        spriteSheetPos: new Position(8, 4),
        name: "drill",
        shopName: "Drill",
        cost: 12,
        descriptionText: "When breaking a safe block all connected safe blocks are also broken. Doesn't collect gold.",
    }),
    moon_flower: new Item({
        spriteSheetPos: new Position(10, 4),
        name: "moon_flower",
        shopName: "Moon Flower",
        cost: 28,
        descriptionText: "Enemies take longer to attack.",
    }),
    carving_knife: new Item({
        spriteSheetPos: new Position(12, 4),
        name: "carving_knife",
        shopName: "Carving Knife",
        cost: 8,
        descriptionText: "Gain 2 gold for every enemy killed.",
    }),
    health_insurance: new Item({
        spriteSheetPos: new Position(14, 4),
        name: "health_insurance",
        shopName: "Health Insurance",
        cost: 22,
        descriptionText: "Gain 1 heart when clearing a level.",
    }),
    whetstone: new Item({
        spriteSheetPos: new Position(0, 5),
        name: "whetstone",
        shopName: "Whetstone",
        cost: 18,
        descriptionText: "Reduces weapon $spdcooldown for 5% per weapon damage.",
    }),
    safety_helmet: new Item({
        spriteSheetPos: new Position(2, 5),
        name: "safety_helmet",
        shopName: "Safety Helmet",
        cost: 22,
        descriptionText: "+1 initial $dfsdefense each fight.",
    }),
    gunpowder: new Item({
        spriteSheetPos: new Position(4, 5),
        name: "gunpowder",
        shopName: "Gunpowder",
        cost: 12,
        descriptionText: "Bombs deal 8 damage.",
    }),
    bracer: new Item({
        spriteSheetPos: new Position(6, 5),
        name: "bracer",
        shopName: "Bracer",
        cost: 36,
        descriptionText: "Adds 0.5 $dfsdefense to your shield.",
    }),
    tool_belt: new Item({
        spriteSheetPos: new Position(8, 5),
        name: "tool_belt",
        shopName: "Tool Belt",
        cost: 26,
        descriptionText: "Allows you to hold a second active item.",
    }),
    spike_polisher: new Item({
        spriteSheetPos: new Position(10, 5),
        name: "spike_polisher",
        shopName: "Spike Polisher",
        cost: 19,
        descriptionText: "Turns gained spikes into reflection.",
    }),
    led_boots: new Item({
        spriteSheetPos: new Position(12, 5),
        name: "led_boots",
        shopName: "Led Boots",
        cost: 24,
        descriptionText: "Increases shield parry bonus to 50%.",
    }),
    charged_ambar: new Item({
        spriteSheetPos: new Position(0, 8),
        name: "charged_ambar",
        shopName: "Charged Ambar",
        cost: 23,
        descriptionText: "Replaces shield parry bonus for a 2 second stun.",
    }),
    empty: new Item({
        spriteSheetPos: new Position(-1, -1),
        name: "empty",
        shopName: "",
        cost: 0,
    }),
};
export default passivesDict;
